version: '3.8'

services:
  local-mongodb:
    image: 'mongo:4.2.16-bionic'
    environment:
      MONGO_INITDB_ROOT: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27018

  # prod-db:
  #   image: 'mongo:4.2.16-bionic'
  #   environment:
  #     MONGO_INITDB_ROOT: logs
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - { MONGO_URI }
